// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbjuypyejbmqfeseejgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNianV5cHllamJtcWZlc2VlamdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NjgxNjksImV4cCI6MjA2OTM0NDE2OX0.OK_Rcs3mHT4B6sOIuSSU5DWRGoL4iTJVv_dgiRgeV50";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});